### ISSUE TITLE
Permission denied?

### ISSUE THREAD

**Issue by deusnovus** [Berikai/bitwig-theme-editor#5]
I just got around using your editor and after attempting to inject my .json file onto the bitwig.jar, I get a Permission Denied notice and when launching Bitwig, it's still in its default state.

Here is the terminal output:

```
java -jar /mnt/external/Dropbox/software/bitwig/bitwig-theme-editor/bitwig-theme-editor.jar /opt/bitwig-studio/bin/bitwig.jar apply current-bitwig-theme.json
Bitwig meets themes... Let's go!
Applying theme from: current-bitwig-theme.json
Exception in thread "main" java.io.FileNotFoundException: /opt/bitwig-studio/bin/bitwig.jar (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:118)
	at dev.berikai.BitwigTheme.asm.JarNode.export(JarNode.java:51)
	at dev.berikai.BitwigTheme.Main.applyTheme(Main.java:93)
	at dev.berikai.BitwigTheme.Main.main(Main.java:57)
```
The problem persists even if I have the bitwig-theme-editor.jar file in my Home directory, so I am not sure whether I'm doing something wrong.

**Comment by deusnovus** [comment]
Nevermind, I forgot it needs `sudo`. Closing now.
